version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "jquery"
  ]